seed: 1
num_worker: 6
work_dir: ./output/original_48_SE/

phase: train

# feeder
feeder: feeders.feeder_ma52_NEW.Feeder
train_feeder_args:
  data_path: new_ma52/json
  label_path: 'train'
  data_type: 'j'
  repeat: 10
  p: 0.3
  debug: False
  partition: True

test_feeder_args:
  data_path: new_ma52/json
  label_path: 'val'
  data_type: 'j'
  repeat: 1
  partition: True

# model
model: model.SkateFormer_SE.SkateFormer_
# weights: output/original_48/runs-34-14926.pt
model_args:
  in_channels: 2
  num_classes: 52
  num_people: 1
  num_points: 48
  kernel_size: 7
  num_heads: 32
  attn_drop: 0.5
  head_drop: 0.0
  rel: True
  drop_path: 0.2
  type_1_size: [8, 12]
  type_2_size: [8, 24]
  type_3_size: [8, 12]
  type_4_size: [8, 24]
  mlp_ratio: 1.0
  index_t: True

#optim
optimizer: AdamW
weight_decay: 0.1
lr_scheduler: cosine
base_lr: 1e-4
min_lr: 1e-5
warmup_lr: 1e-7
warmup_prefix: False
warm_up_epoch: 25

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 100
start_epoch: 0
nesterov: True
grad_clip: True
grad_max: 1.0
loss_type: LSCE
